# Generated by Django 3.2 on 2021-05-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210530_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='entry_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passed_units',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='taken_units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
