# Generated by Django 3.2 on 2021-06-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210531_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gpa',
            new_name='total_gpa',
        ),
        migrations.AddField(
            model_name='student',
            name='last_semester_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='total_units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
