# Generated by Django 3.2 on 2021-06-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210601_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='entry_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_semester_gpa',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passed_units',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='taken_units',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_gpa',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_units',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
