# Generated by Django 3.2 on 2021-06-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210601_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='entry_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_semester_gpa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='passed_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='taken_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_gpa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_units',
            field=models.IntegerField(default=0),
        ),
    ]
