# Generated by Django 3.2 on 2021-06-09 06:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='study',
            new_name='field',
        ),
        migrations.AlterField(
            model_name='chart',
            name='courses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
