# Generated by Django 3.2 on 2021-06-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_alter_chart_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='charts',
            field=models.ManyToManyField(to='charts.Chart'),
        ),
    ]
