# Generated by Django 3.2 on 2021-06-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_remove_coursetracker_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetracker',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
