# Generated by Django 3.2 on 2021-06-12 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210601_1354'),
        ('charts', '0006_coursetracker_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetracker',
            name='unit',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('owner', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
