# Generated by Django 3.2 on 2021-06-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0008_auto_20210612_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='suggested_prerequisites',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chart',
            name='build_date',
            field=models.DateField(default='2021-06-14'),
        ),
    ]
