# Generated by Django 3.2 on 2021-06-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0009_auto_20210614_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetracker',
            name='label',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
