# Generated by Django 3.2 on 2021-06-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0010_alter_coursetracker_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='label',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
