# Generated by Django 3.2 on 2021-06-15 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charts', '0012_coursetracker_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='build_date',
            field=models.DateField(default='2021-06-15'),
        ),
        migrations.CreateModel(
            name='SemesterCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('times', models.TextField(default='')),
                ('time_exam', models.CharField(max_length=100)),
                ('priority', models.BooleanField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('selected', models.BooleanField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_course_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
