# Generated by Django 3.2 on 2021-06-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0014_auto_20210616_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestercourse',
            name='priority',
            field=models.BooleanField(default=0),
        ),
    ]
