# Generated by Django 3.2 on 2021-06-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0015_alter_semestercourse_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestercourse',
            name='selected',
            field=models.BooleanField(default=0),
        ),
    ]
