# Generated by Django 3.2 on 2021-06-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0016_alter_semestercourse_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestercourse',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
